const LESSONS=window.PRIMORIA_LESSONS||[],SCHOOLS=["Western History","Classics","Philosophy","Theology","Law","Political Thought"],KEY="primoria.v2";
let state={tab:"Home",lesson:null,completed:[],bookmarks:[],xp:0,streak:1,lastVisit:null,query:"",school:"All",region:"All"};
try{state={...state,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{}
const today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);
if(state.lastVisit!==today){state.streak=state.lastVisit===yesterday?(state.streak||0)+1:1;state.lastVisit=today;save()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));stats()}function stats(){xp.textContent=state.xp;done.textContent=state.completed.length;marks.textContent=state.bookmarks.length;streak.textContent=state.streak}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function go(t){state.tab=t;state.lesson=null;scrollTo(0,0);render()}function openL(id){state.lesson=id;scrollTo(0,0);render()}
function toggleMark(id){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];save();render()}
function nav(){navEl.innerHTML=["Home","Library","Paths","Bookmarks",...SCHOOLS].map(x=>`<button class="${state.tab===x?"active":""}" onclick="go('${x}')">${x}</button>`).join("")}
function desc(s){return {"Western History":"Egypt, Greece, Rome, England, France, Germany, Spain, and Portugal through primary evidence.","Classics":"Epic, tragedy, poetry, and literature from Homer, Sophocles, Virgil, Ovid, and others.","Philosophy":"Knowledge, virtue, justice, reason, freedom, and the good life in original texts.","Theology":"Foundational biblical and Christian writings, clearly distinguished by genre.","Law":"Written law, procedure, authority, rights, and codification from Babylon to modern Europe.","Political Thought":"Citizenship, sovereignty, consent, democracy, civil society, and power."}[s]}
function card(l){return `<article class="card click" onclick="openL('${l.id}')"><div class="eyebrow">${esc(l.school)} · ${esc(l.region)}</div><h3>${esc(l.title)}</h3><p>${esc(l.author)} · ${esc(l.date)}</p><div class="badges"><span class="badge">${esc(l.path)}</span>${state.completed.includes(l.id)?'<span class="badge">✓ Completed</span>':''}${state.bookmarks.includes(l.id)?'<span class="badge">★ Saved</span>':''}</div></article>`}
function home(){let next=LESSONS.find(l=>!state.completed.includes(l.id))||LESSONS[0];return `<section class="hero"><div class="eyebrow">Primoria · Volume Two</div><h2>Read the texts that shaped Western civilization.</h2><p>A guided primary-source curriculum with connected reading paths, quizzes, bookmarks, progress, and visible source-review labels.</p><div class="actions"><button class="btn primary" onclick="openL('${next.id}')">Continue: ${esc(next.title)}</button><button class="btn" onclick="go('Library')">Explore ${LESSONS.length} lessons</button></div></section><h2 class="section-title">Schools</h2><section class="grid">${SCHOOLS.map(s=>{let a=LESSONS.filter(l=>l.school===s),d=a.filter(l=>state.completed.includes(l.id)).length,p=Math.round(d/a.length*100);return `<article class="card click" onclick="go('${s}')"><div class="eyebrow">${a.length} lessons</div><h3>${s}</h3><p>${desc(s)}</p><div class="progress"><span style="width:${p}%"></span></div><div class="badges"><span class="badge">${d}/${a.length} completed</span></div></article>`}).join("")}</section>`}
function filters(){let regions=[...new Set(LESSONS.map(l=>l.region))].sort();return `<div class="controls"><input value="${esc(state.query)}" placeholder="Search authors, works, themes..." oninput="state.query=this.value;list()"><select onchange="state.school=this.value;list()"><option>All</option>${SCHOOLS.map(s=>`<option ${state.school===s?"selected":""}>${s}</option>`).join("")}</select><select onchange="state.region=this.value;list()"><option>All</option>${regions.map(r=>`<option ${state.region===r?"selected":""}>${esc(r)}</option>`).join("")}</select></div>`}
function filtered(){let q=state.query.toLowerCase();return LESSONS.filter(l=>(!q||JSON.stringify(l).toLowerCase().includes(q))&&(state.school==="All"||l.school===state.school)&&(state.region==="All"||l.region===state.region))}
function list(){let e=document.getElementById("lessonList");if(e){let a=filtered();e.innerHTML=a.length?a.map(card).join(""):'<div class="empty">No lessons match.</div>'}}
function library(){return `<section class="hero"><div class="eyebrow">Primary-source library</div><h2>Browse works, authors, places, and themes.</h2><p>Lesson content is separated from the interface so future works can be added without rebuilding the whole site.</p></section>${filters()}<section id="lessonList" class="grid">${filtered().map(card).join("")}</section>`}
function schoolPage(s){let a=LESSONS.filter(l=>l.school===s);return `<section class="hero"><div class="eyebrow">${a.length} lessons</div><h2>${s}</h2><p>${desc(s)}</p></section><section class="grid" style="margin-top:14px">${a.map(card).join("")}</section>`}
function paths(){let g={};LESSONS.forEach(l=>(g[l.path]??=[]).push(l));return `<section class="hero"><div class="eyebrow">Connected curriculum</div><h2>Follow ideas across works and centuries.</h2><p>Reading paths connect texts around shared questions.</p></section><section class="grid" style="margin-top:14px">${Object.entries(g).map(([p,a])=>`<article class="card click" onclick="state.query='${p}';go('Library')"><div class="eyebrow">Reading path</div><h3>${p}</h3><p>${a.map(x=>x.author).join(" · ")}</p><span class="badge">${a.length} lessons</span></article>`).join("")}</section>`}
function bookmarks(){let a=LESSONS.filter(l=>state.bookmarks.includes(l.id));return `<section class="hero"><div class="eyebrow">Saved works</div><h2>Your bookmarks</h2><p>Saved locally on this device.</p></section><section class="grid" style="margin-top:14px">${a.length?a.map(card).join(""):'<div class="empty">No bookmarks yet.</div>'}</section>`}
function lesson(l){return `<div class="reader-wrap"><div class="backbar"><button class="btn" onclick="go('${l.school}')">← Back</button><button class="btn" onclick="toggleMark('${l.id}')">${state.bookmarks.includes(l.id)?"★ Remove bookmark":"☆ Bookmark"}</button></div><article class="reader"><div class="meta"><span>${esc(l.school)}</span><span>${esc(l.region)}</span><span>${esc(l.date)}</span></div><h2>${esc(l.title)}</h2><p><strong>${esc(l.author)}</strong> · <em>${esc(l.work)}</em></p><div class="notice"><strong>Source status:</strong> ${esc(l.status)}<br><small>${esc(l.source)}</small></div><h3>Context</h3><p>${esc(l.context)}</p><h3>Primary-source passage</h3><div class="quote">“${esc(l.excerpt)}”</div><h3>Vocabulary</h3><div class="vocab">${l.vocabulary.map(v=>`<div><strong>${esc(v[0])}</strong><br>${esc(v[1])}</div>`).join("")}</div><div class="quiz"><h3>Knowledge check</h3>${l.questions.map((q,qi)=>`<div id="q${qi}"><p><strong>${esc(q.prompt)}</strong></p>${q.choices.map((c,ci)=>`<button class="option" onclick="answer('${l.id}',${qi},${ci},this)">${esc(c)}</button>`).join("")}<div class="feedback"></div></div>`).join("")}</div></article></div>`}
function answer(id,qi,ci,b){let l=LESSONS.find(x=>x.id===id),q=l.questions[qi],w=document.getElementById("q"+qi);if(w.dataset.a)return;w.dataset.a=1;[...w.querySelectorAll(".option")].forEach((x,i)=>{x.disabled=true;if(i===q.answer)x.classList.add("correct")});if(ci!==q.answer)b.classList.add("wrong");w.querySelector(".feedback").innerHTML=(ci===q.answer?"Correct. ":"Not quite. ")+esc(q.explanation);if(!state.completed.includes(id)){state.completed.push(id);state.xp+=25;save();w.querySelector(".feedback").innerHTML+=" <strong>Lesson completed: +25 XP.</strong>"}}
function render(){nav();stats();if(state.lesson){main.innerHTML=lesson(LESSONS.find(l=>l.id===state.lesson));return}main.innerHTML=state.tab==="Home"?home():state.tab==="Library"?library():state.tab==="Paths"?paths():state.tab==="Bookmarks"?bookmarks():schoolPage(state.tab)}
const main=document.getElementById("main"),navEl=document.getElementById("nav");render();
